#!/bin/bash
cat src/00-engine-core.js src/05-minigame-shared.js \
    src/10-minigames/*.js \
    src/maps/*.js \
    src/99-engine-tail.js > game.js#!/usr/bin/env bash
# Regenerates game.js from the editable fragments in src/.
#
# Why this exists: game.js is one big closure, and several pieces of state
# (state, player, camera, activeMinigame, ...) are read AND reassigned from
# both the "engine" code and the mini-game code. That rules out real ES
# modules for this split without a much bigger refactor (turning every such
# variable into a shared mutable object first). Concatenation sidesteps that
# entirely: the output is byte-for-byte what you'd get from hand-editing one
# giant file, just with the source kept in three readable pieces.
#
# Usage:
#   bash build.sh
#
# Run this after editing anything in src/, then reload index.html. It's a
# plain `cat` in filename order -- no Node, no npm, no install step.

set -euo pipefail
cd "$(dirname "$0")"

OUT="game.js"

{
  echo "// ============================================================"
  echo "// AUTO-GENERATED by build.sh -- do not hand-edit this file."
  echo "// Source lives in src/00-engine-head.js, src/10-minigames.js,"
  echo "// src/20-engine-tail.js. Edit those, then re-run build.sh."
  echo "// ============================================================"
  cat src/00-engine-head.js
  cat src/10-minigames.js
  cat src/20-engine-tail.js
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines) from src/*.js"
